// sync-web.mjs — copy the web-app source into mobile/www/ where Capacitor
// will pick it up. We do this instead of pointing webDir at the project
// root because the project root has node_modules, .git, models/, llama-cpp/,
// venv_local_ai/ etc. that we MUST NOT bundle into the APK.
//
// Run: npm run sync:web (called automatically by `npm run sync`).

import { mkdir, rm, copyFile, readdir, stat, writeFile } from 'node:fs/promises';
import { resolve, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const WWW  = resolve(__dirname, 'www');

// Files/dirs we ship inside the APK. Everything else is excluded.
// Add new modules here as the codebase grows; the CI audit catches it
// quickly if a needed import is missing because the page won't boot.
const INCLUDE_FILES = [
  'index.html', 'style.css', 'manifest.json', 'sw.js',
  // top-level JS modules
  'main.js', 'setup.js', 'state.js', 'engine.js', 'config.js', 'ui.js',
  'aiHandler.js', 'actionHandler.js', 'gameLoop.js', 'turnManager.js',
  'combat.js', 'resolution.js', 'questProgress.js', 'questDefinitions.js',
  'storyHooks.js', 'storyContinuity.js', 'storyVariations.js',
  'godMode.js', 'memoryRetriever.js', 'schemas.js', 'localAI.js',
  'liteRTBridge.js', 'saveLoad.js', 'storage.js', 'utils.js',
  'initializationManager.js', 'spellUI.js', 'spells.js', 'spellGeneration.js',
  'spellCasting.js', 'jailSystem.js', 'items.js', 'bosses.js',
  'encounters.js', 'characterDevelopment.js', 'difficultyAdaptation.js',
  'adaptiveAbilities.js', 'ageAppropriateReading.js', 'api_new.js',
  'contextManager.js', 'dynamicBosses.js', 'dynamicChoices.js',
  'dynamicEncounters.js', 'dynamicEnemies.js', 'dynamicItems.js',
  'dynamicLocations.js', 'dynamicSpells.js', 'gemmaContextOptimizer.js',
  'gemmaHyperthreading.js', 'inputCache.js', 'loadingManager.js',
  'loadingTips.js', 'localAIOrchestrator.js', 'locations.js',
  'reputationContextualizer.js', 'storyHooks.js', 'themeIntelligence.js',
  'worldEvolution.js', 'storyHooks.js'
];

console.log('Cleaning mobile/www ...');
await rm(WWW, { recursive: true, force: true });
await mkdir(WWW, { recursive: true });

let copied = 0, missing = [];
for (const rel of new Set(INCLUDE_FILES)) {
  const src = resolve(ROOT, rel);
  try {
    await stat(src);
    await copyFile(src, join(WWW, rel));
    copied++;
  } catch {
    missing.push(rel);
  }
}

// Force the Android build to use the LiteRT backend even if some stray
// localStorage entry says otherwise. We do this with a tiny inline
// bootstrap script written into a sibling file the index.html will pick up.
await writeFile(
  join(WWW, 'mobile-bootstrap.js'),
  `// mobile-bootstrap.js — auto-generated by sync-web.mjs.
// Sets sensible defaults for the Capacitor APK on first install.
// IMPORTANT: never overwrites a value the user has already chosen —
// so switching to cloud mode in Settings persists across reloads.
try {
  if (window.Capacitor && typeof window.Capacitor.isNativePlatform === 'function'
      && window.Capacitor.isNativePlatform()) {
    // Default to cloud so the game works immediately on first install.
    // Users can switch to On-Device AI in Settings once the model is downloaded.
    if (!localStorage.getItem('adv.llmBackend')) {
      localStorage.setItem('adv.llmBackend', 'cloud');
    }
    // NOTE: Do NOT hardcode an API key here - GitHub secret-scanning rejects
    // pushes containing OpenRouter keys, and a key in source code is a public
    // key that anyone can scrape. Users paste their own key in
    // Settings -> Cloud AI on first launch.
    if (!localStorage.getItem('adv.cloudProvider')) {
      localStorage.setItem('adv.cloudProvider', 'openrouter');
    }
  }
} catch (_) {}\n`
);

console.log(`✓ Copied ${copied} files to mobile/www/`);
if (missing.length) console.log(`⚠ ${missing.length} file(s) listed but not found (deduped):`, [...new Set(missing)].join(', '));
